In [1]:
#Data cleaning for Botanical Garden Dataset

In [2]:
# Import the required libraries
import pandas as pd
import numpy as np
from pandas_profiling import ProfileReport

In [3]:
#Reading the dataset

df_botanical_garden = pd.read_csv("/Users/ramyakumaresan/Downloads/Botanical Gardens.csv")
df_botanical_garden

,NAME,the_geom,TEL,URL,ADDRESS1,ADDRESS2,CITY,ZIP
0,New York Botanical Garden,POINT (-73.87826809844856 40.8638797881768),(718) 817-8700,http://www.nybg.org/,200th Street and Kazimiroff Blvd,NaN,Bronx,10458
1,Brooklyn Botanic Garden,POINT (-73.96340681975498 40.667315378140806),(718) 623-7200,http://www.bbg.org/,1000 Washington Ave,NaN,Brooklyn,11225
2,Queens Botanical Garden,POINT (-73.82957497018033 40.750456933569126),(718) 886-3800,http://www.queensbotanical.org/,43-50 Main Street,NaN,Flushing,11355
3,Snug Harbor Cultural Center and Botanical Garden,POINT (-74.10455648630429 40.645101267812436),(718) 273-8200,http://www.snug-harbor.org/,1000 Richmond Terrace,NaN,Staten Island,10310

In [4]:
#Profiling the dataset

profile= ProfileReport(df_botanical_garden, title="profile")
profile.to_file("botanical_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [5]:
#Renaming the columns of the dataset

df_botanical_garden = df_botanical_garden.rename(columns={"NAME":"NAME","TEL":"PHONE NO.","ADDRESS1":"ADDRESS","ZIP":"ZIPCODE"})
df_botanical_garden

,NAME,the_geom,PHONE NO.,URL,ADDRESS,ADDRESS2,CITY,ZIPCODE
0,New York Botanical Garden,POINT (-73.87826809844856 40.8638797881768),(718) 817-8700,http://www.nybg.org/,200th Street and Kazimiroff Blvd,NaN,Bronx,10458
1,Brooklyn Botanic Garden,POINT (-73.96340681975498 40.667315378140806),(718) 623-7200,http://www.bbg.org/,1000 Washington Ave,NaN,Brooklyn,11225
2,Queens Botanical Garden,POINT (-73.82957497018033 40.750456933569126),(718) 886-3800,http://www.queensbotanical.org/,43-50 Main Street,NaN,Flushing,11355
3,Snug Harbor Cultural Center and Botanical Garden,POINT (-74.10455648630429 40.645101267812436),(718) 273-8200,http://www.snug-harbor.org/,1000 Richmond Terrace,NaN,Staten Island,10310

In [6]:
#Adding a category column for "Botanical Garden"

df_botanical_garden['CATEGORY'] = "Botanical Garden"
df_botanical_garden

,NAME,the_geom,PHONE NO.,URL,ADDRESS,ADDRESS2,CITY,ZIPCODE,CATEGORY
0,New York Botanical Garden,POINT (-73.87826809844856 40.8638797881768),(718) 817-8700,http://www.nybg.org/,200th Street and Kazimiroff Blvd,NaN,Bronx,10458,Botanical Garden
1,Brooklyn Botanic Garden,POINT (-73.96340681975498 40.667315378140806),(718) 623-7200,http://www.bbg.org/,1000 Washington Ave,NaN,Brooklyn,11225,Botanical Garden
2,Queens Botanical Garden,POINT (-73.82957497018033 40.750456933569126),(718) 886-3800,http://www.queensbotanical.org/,43-50 Main Street,NaN,Flushing,11355,Botanical Garden
3,Snug Harbor Cultural Center and Botanical Garden,POINT (-74.10455648630429 40.645101267812436),(718) 273-8200,http://www.snug-harbor.org/,1000 Richmond Terrace,NaN,Staten Island,10310,Botanical Garden

In [7]:
#Dropping the columns that are not required in the dataset

df_botanical_garden.drop("the_geom",axis =1,inplace=True)
df_botanical_garden.drop("ADDRESS2",axis =1,inplace=True)
df_botanical_garden.drop("CITY",axis =1,inplace=True)
df_botanical_garden

,NAME,PHONE NO.,URL,ADDRESS,ZIPCODE,CATEGORY
0,New York Botanical Garden,(718) 817-8700,http://www.nybg.org/,200th Street and Kazimiroff Blvd,10458,Botanical Garden
1,Brooklyn Botanic Garden,(718) 623-7200,http://www.bbg.org/,1000 Washington Ave,11225,Botanical Garden
2,Queens Botanical Garden,(718) 886-3800,http://www.queensbotanical.org/,43-50 Main Street,11355,Botanical Garden
3,Snug Harbor Cultural Center and Botanical Garden,(718) 273-8200,http://www.snug-harbor.org/,1000 Richmond Terrace,10310,Botanical Garden

In [8]:
#Adding the additional details column

df_botanical_garden["ADDITIONAL DETAILS"] = 'Not Available'
df_botanical_garden

,NAME,PHONE NO.,URL,ADDRESS,ZIPCODE,CATEGORY,ADDITIONAL DETAILS
0,New York Botanical Garden,(718) 817-8700,http://www.nybg.org/,200th Street and Kazimiroff Blvd,10458,Botanical Garden,Not Available
1,Brooklyn Botanic Garden,(718) 623-7200,http://www.bbg.org/,1000 Washington Ave,11225,Botanical Garden,Not Available
2,Queens Botanical Garden,(718) 886-3800,http://www.queensbotanical.org/,43-50 Main Street,11355,Botanical Garden,Not Available
3,Snug Harbor Cultural Center and Botanical Garden,(718) 273-8200,http://www.snug-harbor.org/,1000 Richmond Terrace,10310,Botanical Garden,Not Available

In [9]:
#Rearranging the columns in the dataframe

df_botanical_garden = df_botanical_garden[["CATEGORY", "NAME", "ADDRESS", "ZIPCODE", "PHONE NO.", "URL", "ADDITIONAL DETAILS"]]
df_botanical_garden

,CATEGORY,NAME,ADDRESS,ZIPCODE,PHONE NO.,URL,ADDITIONAL DETAILS
0,Botanical Garden,New York Botanical Garden,200th Street and Kazimiroff Blvd,10458,(718) 817-8700,http://www.nybg.org/,Not Available
1,Botanical Garden,Brooklyn Botanic Garden,1000 Washington Ave,11225,(718) 623-7200,http://www.bbg.org/,Not Available
2,Botanical Garden,Queens Botanical Garden,43-50 Main Street,11355,(718) 886-3800,http://www.queensbotanical.org/,Not Available
3,Botanical Garden,Snug Harbor Cultural Center and Botanical Garden,1000 Richmond Terrace,10310,(718) 273-8200,http://www.snug-harbor.org/,Not Available

In [10]:
#Checking for missing values

for c in df_botanical_garden.columns:
    miss = df_botanical_garden[c].isnull().sum()
    
    if miss > 0 :
        print("{} has {} missing value(s)".format(c,miss))
    else:
        print("{} has NO missing value!".format(c))

CATEGORY has NO missing value!
NAME has NO missing value!
ADDRESS has NO missing value!
ZIPCODE has NO missing value!
PHONE NO. has NO missing value!
URL has NO missing value!
ADDITIONAL DETAILS has NO missing value!

In [12]:
#Writing the dataframe to a csv file
df_botanical_garden.to_csv('/Users/ramyakumaresan/Downloads/Botanical_Gardens.csv' ,index=False)